<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="TI1.css">
    <title>TI1 Juliusz Parchem</title>
  </head>
  <body>
    <div class="green">
 <h1>Potęgowanie i pierwiastkowanie w PHP</h1>
 <h2>Wstęp</h2>
 <p>Potęgowanie i pierwiastkowanie to jedne z podstawowych działań matematycznych. Język PHP posiada wbudowane funkcje i operator umożliwiające
    wykonywanie tych działań, są to:</p>
    <ul>
        <li>Funkcja pow()</li>
        <li>Operator **</li>
        <li>Funckja sqrt()</li>
    </ul>
    <p>Poniżej zostanie omówiony każdy z powyższych elementów.</p>
 <h2>Funkcja pow()</h2>
 <p>Funkcja pow() jest podstawową funkcją używaną przy działaniach potęgowania i pierwiastkowania. Przyjmuje dwa parametry, kolejno podstawę i wykładnik.</p>
 <h4>Składnia</h4>
 <p class="skladnia">pow(&lt;podstawa&gt;,&lt;wykładnik&gt;);</p>
 <h4><a href="https://foka.umg.edu.pl/~s48230/Semestr4/Technologie%20Internetowe/Prez1/P1.php">Przykład 1 - Potęgowanie</a></h4>
 <div class="row">
    <div class="column">
        <p class="gora">KOD</p>
        <p class="kod">&lt;?php<br>
            &emsp;echo pow(2, 0);<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo pow(2, 1);<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo pow(2, 2);<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo pow(2, 3);<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo pow(2, 4);<br>
        ?&gt;</p>
    </div>
    <div class="column">
        <p class="gora">REZULTAT</p>
        <p class="kod">1<br>
        2<br>
    4<br>
    8<br>
    16<br>
  </p>
  </div></div>
  <h4><a href="https://foka.umg.edu.pl/~s48230/Semestr4/Technologie%20Internetowe/Prez1/P2.php">Przykład 2 - Pierwiastkowanie</a></h4>
<div class="row">
   <div class="column">
       <p class="gora">KOD</p>
       <p class="kod">&lt;?php<br>
            &emsp;echo pow(1, 1/2);<br>
            &emsp;echo "&lt;br&gt;";<br>
           &emsp;echo pow(8, 1/3);<br>
           &emsp;echo "&lt;br&gt;";<br>
           &emsp;echo pow(81, 1/4);<br>
           &emsp;echo "&lt;br&gt;";<br>
           &emsp;echo pow(1024, 1/5);<br>
           &emsp;echo "&lt;br&gt;";<br>
           &emsp;echo pow(15625, 1/6);<br>
       ?&gt;</p>
   </div>
   <div class="column">
       <p class="gora">REZULTAT</p>
       <p class="kod">1<br>
       2<br>
   3<br>
   4<br>
   5<br>
 </div></div>
 <br><h2>Operator **</h2>
 <p>W wersji języka PHP 5.6 wprowadzono operator potęgowania. Używa się go w taki sam sposób jak inne podstawowe znaki matematyczne takie jak plus i minus.</p>
 <h4>Składnia</h4>
 <p class="skladnia">&lt;podstawa&gt;**&lt;wykładnik&gt;;</p>
 <h4><a href="https://foka.umg.edu.pl/~s48230/Semestr4/Technologie%20Internetowe/Prez1/P3.php">Przykład 1 - Potęgowanie</a></h4>

 <div class="row">
    <div class="column">
        <p class="gora">KOD</p>
        <p class="kod">&lt;?php<br>
            &emsp;echo 2**0;<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo 2**1;<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo 2**2;<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo 2**3;<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo 2**4;<br>
        ?&gt;</p>
    </div>
    <div class="column">
        <p class="gora">REZULTAT</p>
        <p class="kod">1<br>
        2<br>
    4<br>
    8<br>
    16<br>
  </div></div>
  <h4><a href="https://foka.umg.edu.pl/~s48230/Semestr4/Technologie%20Internetowe/Prez1/P4.php">Przykład 2 - Pierwiastkowanie</a></h4>
<div class="row">
   <div class="column">
       <p class="gora">KOD</p>
       <p class="kod">&lt;?php<br>
            &emsp;echo 1**(1/2);<br>
            &emsp;echo "&lt;br&gt;";<br>
           &emsp;echo 8**(1/3);<br>
           &emsp;echo "&lt;br&gt;";<br>
           &emsp;echo 81**(1/4);<br>
           &emsp;echo "&lt;br&gt;";<br>
           &emsp;echo 1024**(1/5);<br>
           &emsp;echo "&lt;br&gt;";<br>
           &emsp;echo 15625**(1/6);<br>
           ?&gt;</p> 
   </div>
   <div class="column">
       <p class="gora">REZULTAT</p>
       <p class="kod">1<br>
       2<br>
   3<br>
   4<br>
   5<br>
 </div></div>  
 <p class="uwaga">Uwaga! W przypadku pierwiastkowania, trzeba pamiętać aby wykładnik znajdował się w nawiasie!</p>
 <br><h2>Funkcja sqrt()</h2>
 <p>Funkcja sqrt() w przeciwienstwie do wcześniej wspomnianych metod, tyczy się jedynie pierwiastkowania. Zwraca ona pierwiastek kwadratowy zadanego argumentu.</p>
 <h4>Składnia</h4>
 <p class="skladnia">sqrt(&lt;podstawa&gt;);</p>
 <h4><a href="https://foka.umg.edu.pl/~s48230/Semestr4/Technologie%20Internetowe/Prez1/P5.php">Przykład 1</a></h4>
 <div class="row">
    <div class="column">
        <p class="gora">KOD</p>
        <p class="kod">&lt;?php<br>
            &emsp;echo sqrt(1);<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo sqrt(4);<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo sqrt(9);<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo sqrt(16);<br>
            &emsp;echo "&lt;br&gt;";<br>
            &emsp;echo sqrt(25);<br>
        ?&gt;</p>
    </div>
    <div class="column">
        <p class="gora">REZULTAT</p>
        <p class="kod">1<br>
        2<br>
    3<br>
    4<br>
    5<br>
  </div></div></div>

















  <div class="red">
 <h1 class="red">Wyjątki, throw, try i catch w PHP</h1>
 <h2 class="red">Wyjątki</h2>
 <p>W PHP, wyjątki pozwalają na eliminację błędów które uniemożliwiają dalsze funkcjonowanie aplikacji. W tym celu
    wykorzystuje się trzy funckje wyjątków:
 </p>
    <ul>
        <li>throw</li>
        <li>try</li>
        <li>catch</li>
    </ul>
    <p>Ponieżej zostanie omówiony każdy z powyższych elementów.</p>
 <h2>Throw</h2>
 <p>Funkcja throw pozwala określić jaki wyjątek ma zostać "wyrzucony" w przypadku wystąpienia błędu. Nadaje się mu określoną wiadomość oraz kod który jest następnie wyświetlany użytkownikowi.</p>
 <h4>Składnia</h4>
 <p class="skladnia">function &lt;nazwa funkcji&gt;(&lt;parametry&gt;){<br>
    &emsp;if(&lt;warunek wystąpienia błędu&gt;) {<br>
        &emsp;&emsp;throw new Exception("&lt;wiadomość błędu&gt;",&lt;kod błędu&gt;);<br>
        &emsp;}<br>
        &emsp;&emsp;return &lt;wartość którą funkcja zwraca bez wystąpienia błędu&gt;;<br>
        &emsp;} </p>
 <h4><a href="https://foka.umg.edu.pl/~s48230/Semestr4/Technologie%20Internetowe/Prez1/P6.php">Przykład 1</a></h4>
 <p>Aby zaprezentować przykład skonstruowałem funkcję "sprawdzam", która w przypadku gdy parametr "$numer" jest większy od 10 zwróci wyjątek z wiadomością "Wprowadzona wartość jest większa od 10" oraz kodem błędu 5.</p>
 <div class="row">
    <div class="column">
        <p class="gora">KOD</p>
        <p class="kod">&lt;?php<br>
            &emsp;function sprawdzam($numer) {<br>
            &emsp;&emsp;if($numer&gt;10) {<br>
            &emsp;throw new Exception("Wprowadzona wartość jest większa od 10.",5);<br>
            &emsp;}<br>
            &emsp;&emsp;return true;<br>
            &emsp;}<br>
            <br>
            &emsp;sprawdzam(11);<br>
            <br>
            &emsp;echo "Przez błąd, ta wiadomość nie zostanie wyświetlona.";<br>
        ?&gt;</p>
    </div>
    <div class="column">
        <p class="gora">REZULTAT</p>
        <p class="kod">Fatal error: Uncaught Exception: Wprowadzona wartość jest większa od 10. in /home/s48230/public_html/Semestr4/Technologie Internetowe/Prez1/P6.php:11 Stack trace: #0 /home/s48230/public_html/Semestr4/Technologie Internetowe/Prez1/P6.php(16): sprawdzam() #1 {main} thrown in /home/s48230/public_html/Semestr4/Technologie Internetowe/Prez1/P6.php on line 11</p>
  </div></div>
  <p>Jak widać, wprowadzona wartość 11 dla funkcji "sprwadzam" wyrzuciła wyjątek z przygotowaną przez nas wiadomością. Aplikacja przestała jednak działać i nie uruchomiła reszty kodu, aby temu zapobiec wykorzystamy funkcje try oraz catch.</p>
 <br><h2>Try i catch</h2>
 <p>Gdy już umiemy przygotować wiadomość oraz kod dla występującego wyjątku, kolejnym krokiem będzie przygotowanie aby aplikacja nie przestawała działać podczas jego wystąpienia. 
    Do tego posłuży try, w którym umieszczone zostaną funkcje które podejrzewamy o wystąpienie wyjątki, a aplikacji po ich wykonaniu nie zatrzyma się.
    <br><br>
    Nierozłącznym elementem try jest catch, które pozwala wychwycić wyjątek który występił w obrębie try. Dzięki niemu będziemy mogli określić co aplikacja ma zrobić w przypadku wystąpienia wyjątku.
 </p>
 <h4>Składnia try</h4>
 <p class="skladnia">try {<br><br>
    &lt;podejrzane funkcje&gt;;<br><br>
 }
</p>
<h4>Składnia catch</h4>
 <p class="skladnia">catch(Exception $e) {<br><br>
    &lt;funkcje które zostaną wykonane po wystąpieniu wyjątku&gt;;<br><br>
 }
</p>
 <h4><a href="https://foka.umg.edu.pl/~s48230/Semestr4/Technologie%20Internetowe/Prez1/P7.php">Przykład 1</a></h4>

 <div class="row">
    <div class="column">
        <p class="gora">KOD</p>
        <p class="kod1">&lt;?php<br>
            &emsp;function sprawdzam($numer) {<br>
            &emsp;&emsp;if($numer&gt;10) {<br>
            &emsp;throw new Exception("Wprowadzona wartość jest większa od 10.",5);<br>
            &emsp;}<br>
            &emsp;&emsp;return true;<br>
            &emsp;}<br>
            <br>
            &emsp;try {<br>
                &emsp;&emsp;sprawdzam(11);<br>
                &emsp;&emsp;echo "Nie wystąpił żaden błąd";<br>

            &emsp;}<br><br>
            &emsp;catch(Exception $e) {<br>
                &emsp;&emsp;echo "Wiadomość błędu: ".$e-&gt;getMessage();<br>
                &emsp;&emsp;echo "&lt;br&gt;";<br>
                &emsp;&emsp;echo "Kod błędu: ".$e-&gt;getCode();<br>
                &emsp;}
                <br>
        ?&gt;</p>
    </div>
    <div class="column">
        <p class="gora">REZULTAT</p>
        <p class="kod1">Wiadomość błędu: Wprowadzona wartość jest większa od 10.<br>
            Kod błędu: 5
  </div></div>
  <p>W obrębie funkcji try została umieszczona wcześniej przygotowana przez nas funkcja zwracająca wyjątek, który następnie został wyłapany w obrębie funkcji catch w której została przygotowana wiadomość towarzysząca występującemu wyjątkowi. Warto zauważyć, że przez występujący wyjątek w obrębie funkcji try, funkcja echo nie została wywołana.<br><br>
    Aby przygotować formułkę przywoływaną przez catch, możemy posłużyć się wiadomością i kodem określonym przez nas w funkcji throw, do ich wywołania wykorzystujemy:</p>
    <ul>
        <li>$e-&gt;getMessage() które zwraca określoną wiadomość błędu.</li>
        <li>$e-&gt;getCode() które zwraca określony kod błędu.</li>
    </ul>
    
  <h4><a href="https://foka.umg.edu.pl/~s48230/Semestr4/Technologie%20Internetowe/Prez1/P8.php">Przykład 2</a></h4>
  <div class="row">
    <div class="column">
        <p class="gora">KOD</p>
        <p class="kod1">&lt;?php<br>
            &emsp;function sprawdzam($numer) {<br>
            &emsp;&emsp;if($numer&gt;10) {<br>
            &emsp;throw new Exception("Wprowadzona wartość jest większa od 10.",5);<br>
            &emsp;}<br>
            &emsp;&emsp;return true;<br>
            &emsp;}<br>
            <br>
            &emsp;try {<br>
                &emsp;&emsp;sprawdzam(9);<br>
                &emsp;&emsp;echo "Nie wystąpił żaden błąd";<br>

            &emsp;}<br><br>
            &emsp;catch(Exception $e) {<br>
                &emsp;&emsp;echo "Wiadomość błędu: ".$e-&gt;getMessage();<br>
                &emsp;&emsp;echo "&lt;br&gt;";<br>
                &emsp;&emsp;echo "Kod błędu: ".$e-&gt;getCode();<br>
                &emsp;}
                <br>
        ?&gt;</p>
    </div>
    <div class="column">
        <p class="gora">REZULTAT</p>
        <p class="kod1">Nie wystąpił żaden błąd<br>
  </div></div>
 <p>W tym przypadku try nie wyłapało błędu i wykonało wszystkie znajdujące się w jego obrębie funkcje.</p>
</div>










<div class="blue">
    <h1>Połączenie pierwiastkowania i wyjątków</h1>
    <h4><a href="https://foka.umg.edu.pl/~s48230/Semestr4/Technologie%20Internetowe/Prez1/P9.php">Przykład 1</a></h4>
    <div class="row">
      <div class="column">
          <p class="gora">KOD</p>
          <p class="kod2">&lt;?php<br>
              &emsp;function pierwiastekdrugiegostopnia($podstawa) {<br>
              &emsp;&emsp;if($podstawa&lt;0) {<br>
              &emsp;throw new Exception("Podstawa nie może być ujemna dla pierwiastka<br>&emsp;drugiego stopnia",123456789);<br>
              &emsp;}<br>
              &emsp;&emsp;echo "Pierwiastek drugiego stopnia dla ".$podstawa." wynosi: ".$podstawa**(1/2)."&lt;br&gt;";<br>
              &emsp;}<br>
              <br>
              &emsp;try {<br>
                  &emsp;&emsp;pierwiastekdrugiegostopnia(1);<br>
              &emsp;}<br><br>
              &emsp;catch(Exception $e) {<br>
                  &emsp;&emsp;echo "Wiadomość błędu: ".$e-&gt;getMessage();<br>
                  &emsp;&emsp;echo "&lt;br&gt;";<br>
                  &emsp;&emsp;echo "Kod błędu: ".$e-&gt;getCode();<br>
                  &emsp;}
                  <br><br>
            &emsp;try {<br>
                    &emsp;&emsp;pierwiastekdrugiegostopnia(-1);<br>
                &emsp;}<br><br>
                &emsp;catch(Exception $e) {<br>
                    &emsp;&emsp;echo "Wiadomość błędu: ".$e-&gt;getMessage();<br>
                    &emsp;&emsp;echo "&lt;br&gt;";<br>
                    &emsp;&emsp;echo "Kod błędu: ".$e-&gt;getCode();<br>
                    &emsp;}
                    <br>
          ?&gt;</p>
      </div>
      <div class="column">
          <p class="gora">REZULTAT</p>
          <p class="kod2">Pierwiastek drugiego stopnia dla 1 wynosi: 1<br>
            Wiadomość błędu: Podstawa nie może być ujemna dla pierwiastka drugiego stopnia<br>
            Kod błędu: 123456789<br>
    </div></div>
    <p>Przygotowałem funkcję która zwraca pierwiastek kwadratowy podanej wartości. Wprowadziłem w niej wyjątek który wyświetla się gdy podana wartość jest ujemna. W rezultacie można zaobserować efekt dla poprawnie i niepoprawnie wprowadzonych wartości. </p>
<p class="uwaga">Uwaga! Trzeba pamiętać, że po każdym wywołaniu funkcji try musi występować funkcja catch.</p>  

</div>

</body>
</html>
